<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Product Description') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
    <?php
    /*
     * @TODO clean up additional info
     */
    ?>
    <div class="product-collateral">

        <div id="product-collateral-tabs">
            <?php
            $tabs = array();
            $titles = array(
                'description' => $this->__('Details'),
                'additional' => $this->__('Additional Information')
            );
            foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):
                $tabs[] = array(
                    'alias' => $alias,
                    'tab_title' => ($this->getChildData($alias, 'title')) ? $this->getChildData($alias, 'title') : $titles[$alias],
                    'block_title' => $this->getChildData($alias, 'title'),
                    'html' => $html
                );
            endforeach;
            ?>

            <ul class="tab-list">
                <?php $first = true; foreach ($tabs as $tab): ?>
                    <li class="<?php echo $tab['alias']; ?>"><a href="#box-<?php echo $tab['alias']; ?>"<?php if ($first) echo ' class="active"'; ?>><?php echo $tab['tab_title']; ?></a></li>
                <?php $first = false; endforeach; ?>
                <li class="reviews"><a href="#customer-reviews"<?php if ($first) echo ' class="active"'; ?>><?php echo $this->__('Reviews'); ?></a></li>
            </ul>

            <?php $first = true; foreach ($tabs as $tab): ?>
                <div class="box-collateral box-<?php echo $tab['alias']; if ($first) echo ' active'; ?>" id="box-<?php echo $tab['alias']?>">
                    <?php if ($tab['block_title']): ?>
                        <h2 class="box-collateral-title"><?php echo $tab['block_title']; ?></h2>
                    <?php endif; ?>
                    <?php echo $tab['html']; ?>
                </div>
            <?php $first = false; endforeach; ?>
            <div class="box-collateral box-reviews <?php if ($first) echo ' active'; ?>" id="customer-reviews">
                <?php echo $this->getChildHtml('product_reviews'); ?>
            </div>
        </div><!--/product-collateral-tabs-->

        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>

    </div><!--/product-collateral-->

</div><!--/product-view-->
