<?php
/**
 * Subcategory list block
 *
 * @package InverseParadox_Boilerplate
 * @author Amanda Mitchell
 * @see InverseParadox_Boilerplate_Block_Category_list
 */
?>
<ul class="subcategory-list">
    <?php $i = 0; foreach ($this->getCurrentSubcategories() as $_subcat): ?>
        <?php $i++; ?>
        <li class="<?php echo $this->helper('ipboilerplate')->getColumnClasses($i); ?>">
            <a href="<?php echo $_subcat->getUrl(); ?>"><img src="<?php echo Mage::helper('ipboilerplate/category')->getCategoryThumb($_subcat, 193, 386); ?>" alt="" /></a>
            <h3><a href="<?php echo $_subcat->getUrl(); ?>"><?php echo $_subcat->getName(); ?></a></h3>
        </li>
    <?php endforeach; ?>
</ul>