<ul class="subcategory-list">
    <?php $i = 0; foreach ($this->getCurrentSubcategories() as $_subcat): ?>
        <?php
        $i++;
        $itemclass = '';
        if ($i % 2 == 0) {
            $itemclass = 'even';
        } else {
            $itemclass = 'odd';
        }
        if ($i % 3 == 0) {
            $itemclass .= ' third';
        } else if (($i - 1) % 3 == 0) {
            $itemclass .= ' after-third';
        }
        if ($i % 4 == 0) {
            $itemclass .= ' fourth';
        } else if (($i - 1) % 4 == 0) {
            $itemclass .= ' after-fourth';
        }
        if ($i % 5 == 0) {
            $itemclass .= ' fifth';
        } else if (($i - 1) % 5 == 0) {
            $itemclass .= ' after-fifth';
        }
        ?>
        <li class="<?php echo $itemclass; ?>">
            <a href="<?php echo $_subcat->getUrl(); ?>"><img src="<?php echo Mage::helper('ipboilerplate/category')->getCategoryThumb($_subcat, 193, 386); ?>" alt="" /></a>
            <h3><a href="<?php echo $_subcat->getUrl(); ?>"><?php echo $_subcat->getName(); ?></a></h3>
        </li>
    <?php endforeach; ?>
</ul>