<?php
/*
 * @TODO add doc tag
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php if( $this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
        <div class="data-table" id="my-reviews-table">
            <?php $_i = 0; $_max = count($this->getCollection()); ?>
            <?php foreach ($this->getCollection() as $_review): ?>
                <?php $_i++; ?>
                <div class="table-row table-body-row<?php if ($_i == 1) echo ' first'; if ($_i == $_max) echo ' last'; if ($_i % 2 == 0) echo ' even'; else echo ' odd'; ?>">
                    <div class="table-cell first col-date"><span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></div>
                    <div class="table-cell col-name"><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h2></div>
                    <div class="table-cell col-rating">
                    <?php if($_review->getSum()): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    <?php endif; ?>
                    </div>
                    <div class="table-cell col-detail"><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></div>
                    <div class="table-cell last col-link"><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr"><?php echo $this->__('View Details') ?></a></div>
                </div>
            <?php endforeach; ?>
        </div>
        <script type="text/javascript">decorateTable('my-reviews-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
