<?php
/*
 * @TODO Move review form to layout
 */
$helper_block = Mage::getSingleton('core/layout')->createBlock('review/helper');
$helper_block->addTemplate('form', 'review/helper/summary_form.phtml');
?>

<?php $_product = $this->getProduct(); ?>

<h2 class="box-collateral-title"><?php echo $this->__('Customer Reviews') ?></h2>
<div class="box-collateral-content">
<?php echo $helper_block->getSummaryHtml($_product, 'form', true); ?>


<?php if ($helper_block->getReviewsCount()):?>
    <p class="review-count"><?php echo $this->__('%s Review(s)', $helper_block->getReviewsCount()) ?></p>
<?php endif;?>

<?php echo $this->getChildHtml('review_rating'); ?>

<?php $_items = $this->getReviewsCollection()->getItems();?>
<?php if (count($_items)):?>
    <dl>
    <?php $first = true; ?>
    <?php foreach ($_items as $_review):?>
        <div class="review-item<?php if ($first) echo ' first'; ?>">
            <?php $_votes = $_review->getRatingVotes(); ?>
            <?php if (count($_votes)): ?>
            <table class="ratings-table">
                <col width="1" />
                <col />
                <tbody>
                    <?php foreach ($_votes as $_vote): ?>
                    <tr>
                        <th>
                            <?php echo $this->escapeHtml($_vote->getRatingCode()) ?>
                        </th>
                        <td>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php endif; ?>

            <dt<?php if (count($_votes)): ?> class="with-rating"<?php endif; ?>>
                <?php echo $this->htmlEscape($_review->getTitle()) ?>
            </dt>
            <dd<?php if (count($_votes)): ?> class="with-rating"<?php endif; ?>>
                
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                <small class="meta"><?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?> <em><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></em></small>
            </dd>
        </div>
    <?php $first = false; endforeach; ?>
    </dl>
    <?php echo $this->getChildHtml('toolbar') ?>
<?php endif;?>
<?php echo $this->getChildHtml('review_form') ?>
</div>